openapi: 3.0.3
info:
  title: MOLIM E-Invoicing API
  version: 1.0.0
  description: Auto-generated OpenAPI specification from Postman collection (mirrors all endpoints exactly).
servers:
  -
    url: http://{remote_hostname}:{port}
    variables:
      remote_hostname:
        default: api.example.com
      port:
        default: 80
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
paths:
  /v1/e-invoicing/auth:
    post:
      summary: Auth
      parameters:
      responses:
        200:
          description: Successful response
      requestBody:
        required: True
        content:
          application/json:
            schema:
              type: object
            example:
              vat_number: 311262046600003
              username: api
              secret: W3lc0m32eg$@p!
  /v1/e-invoicing/onboardings:
    post:
      summary: Onboard Both
      parameters:
      responses:
        200:
          description: Successful response
      requestBody:
        required: True
        content:
          application/json:
            schema:
              type: object
            example:
              otp: 507216
              vat_number: 311262046600003
              device_id: 04-LEI
              invoice_type: both
              org_name: Goagile Technologies
              org_unit: Riyadh
              business_category: IT
              registered_address: Al-Morabba
              country_code: SA
              email_id: support@goagile.com
      security:
        -
          BearerAuth:
    get:
      summary: List Onboardings
      parameters:
      responses:
        200:
          description: Successful response
      security:
        -
          BearerAuth:
  /v1/e-invoicing/{onboard_id}/invoices:
    post:
      summary: Advance payment
      parameters:
        -
          name: onboard_id
          in: path
          required: True
          schema:
            type: string
      responses:
        200:
          description: Successful response
      requestBody:
        required: True
        content:
          application/json:
            schema:
              type: object
            example: {
  "invoice_number": "adv_payment_note",
  "invoice_type": "standard",
  "is_advance_payment": true,
  "issue_date": "2023-08-19",
  "issue_time": "10:09:00",
  "due_date": "2023-08-20",
  "payment_means": "cash",
  "payment_means_instruction_note": "",
  "actual_delivery_date": "2023-08-21",
  "supplier_info": {
    "vat_number": "311262046600003",
    "tax_type": "VAT",
    "registration_name": "Goagile & Technologies",
    "address": {
      "street_name": "some street",
      "building_number": "1232",
      "plot_identification": "123",
      "city_subdivision_name": "3232112",
      "city_name": "Riyadh",
      "postal_zone": "54321",
      "country": "SA"
    },
    "party_identification": {
      "scheme": "CRN",
      "id": "2332132133"
    }
  },
  "customer_info": {
    "vat_number": "2323233325",
    "tax_type": "VAT",
    "registration_name": "ABC & Inc.",
    "address": {
      "street_name": "some street",
      "building_number": "1232",
      "plot_identification": "123",
      "city_subdivision_name": "3232112",
      "city_name": "Riyadh",
      "postal_zone": "12345",
      "country": "SA"
    },
    "party_identification": {
      "scheme": "NAT",
      "id": "767687876"
    }
  },
  "allowance_charge": {
    "charge_indicator": false,
    "reason": "discount",
    "amount": 0,
    "currency": "SAR",
    "tax_category": {
      "id": "S",
      "percent": 15,
      "tax_type": "VAT"
    }
  },
  "tax_total": {
    "currency": "SAR",
    "tax_amount": 15000.00,
    "tax_subtotal": {
      "taxable_amount": 100000.00,
      "tax_amount": 15000.00,
      "tax_percent": 15,
      "tax_category": {
        "id": "S",
        "percent": 15,
        "tax_type": "VAT"
      }
    }
  },
  "legal_monitory_total": {
    "total_amount": 100000.00,
    "tax_exclusive_amount": 100000.00,
    "tax_inclusive_amount": 115000.00,
    "allowance_total_amount": 0,
    "prepaid_amount": 0,
    "payable_amount": 115000.00
  },
  "invoice_lines": [
    {
      "id": "1",
      "unit_code": "pce",
      "quantity": 1,
      "amount": 100000.00,
      "tax_total": {
        "currency": "SAR",
        "tax_amount": 15000.00,
        "rounding_amount": 115000.00,
        "tax_subtotal": {
          "taxable_amount": 100000,
          "tax_amount": 15000,
          "tax_category": {
            "id": "S",
            "percent": 15,
            "tax_type": "VAT"
          }
        }
      },
      "item": {
        "name": "Advance Payment",
        "classified_tax_category": {
          "id": "S",
          "percent": 15,
          "tax_type": "VAT"
        }
      },
      "price": {
        "currency": "SAR",
        "price_per_unit": 100000,
        "base_quantity": 1,
        "allowance_charge": { 
            "charge_indicator": false,
            "reason": "discount",
            "amount": 0,
            "base_amount": 100000,
            "currency": "SAR"
          }
      }
    }
  ]
}


Advance Payment
===================
{
  "invoice_number": "adv_payment_adjusted-001",
  "invoice_type": "standard",
  "issue_date": "2023-09-20",
  "issue_time": "10:09:00",
  "due_date": "2023-08-20",
  "payment_means": "cash",
  "payment_means_instruction_note": "",
  "actual_delivery_date": "2023-09-21",
  "supplier_info": {
    "vat_number": "311262046600003",
    "tax_type": "VAT",
    "registration_name": "Goagile & Technologies",
    "address": {
      "street_name": "some street",
      "building_number": "1232",
      "plot_identification": "123",
      "city_subdivision_name": "3232112",
      "city_name": "Riyadh",
      "postal_zone": "54321",
      "country": "SA"
    },
    "party_identification": {
      "scheme": "CRN",
      "id": "2332132133"
    }
  },
  "customer_info": {
    "vat_number": "2323233325",
    "tax_type": "VAT",
    "registration_name": "ABC & Inc.",
    "address": {
      "street_name": "some street",
      "building_number": "1232",
      "plot_identification": "123",
      "city_subdivision_name": "3232112",
      "city_name": "Riyadh",
      "postal_zone": "12345",
      "country": "SA"
    },
    "party_identification": {
      "scheme": "NAT",
      "id": "767687876"
    }
  },
  "allowance_charge": {
    "charge_indicator": false,
    "reason": "discount",
    "amount": 0,
    "currency": "SAR",
    "tax_category": {
      "id": "S",
      "percent": 15,
      "tax_type": "VAT"
    }
  },
  "tax_total": {
    "currency": "SAR",
    "tax_amount": 7500,
    "tax_subtotal": {
      "taxable_amount": 50000.00,
      "tax_amount": 7500.00,
      "tax_percent": 15,
      "tax_category": {
        "id": "S",
        "percent": 15,
        "tax_type": "VAT"
      }
    }
  },
  "legal_monitory_total": {
    "total_amount": 50000.00,
    "tax_exclusive_amount": 50000.00,
    "tax_inclusive_amount": 57500.00,
    "allowance_total_amount": 0,
    "prepaid_amount": 28750.00,
    "payable_amount": 28750.00
  },
  "invoice_lines": [
    {
      "id": "1",
      "unit_code": "pce",
      "quantity": 200,
      "amount": 50000.00,
      "tax_total": {
        "currency": "SAR",
        "tax_amount": 7500.00,
        "rounding_amount": 57500.00
      },
      "item": {
        "name": "Mouse",
        "classified_tax_category": {
          "id": "S",
          "percent": 15,
          "tax_type": "VAT"
        }
      },
      "price": {
        "currency": "SAR",
        "price_per_unit": 250.00,
        "base_quantity": 1,
        "allowance_charge": { 
            "charge_indicator": false,
            "reason": "discount",
            "amount": 0,
            "base_amount": 250.00,
            "currency": "SAR"
          }
      }
    },
    {
      "id": "2",
      "unit_code": "pce",
      "quantity": 1,
      "amount": 0,
      "doc_ref": {
        "id": "adv_payment_note",
        "issue_date": "2023-08-19",
        "issue_time": "10:09:00"
      },
      "tax_total": {
        "currency": "SAR",
        "tax_amount": 0,
        "rounding_amount": 0,
        "tax_subtotal": {
          "taxable_amount": 25000,
          "tax_amount": 3750.00,
          "tax_category": {
            "id": "S",
            "percent": 15,
            "tax_type": "VAT"
          }
        }
      },
      "item": {
        "name": "Prepayment Adjustment",
        "classified_tax_category": {
          "id": "S",
          "percent": 15,
          "tax_type": "VAT"
        }
      },
      "price": {
        "currency": "SAR",
        "price_per_unit": 0
      }
    }
  ]
}
      security:
        -
          BearerAuth:
    get:
      summary: List Invoices By Filter
      parameters:
        -
          name: onboard_id
          in: path
          required: True
          schema:
            type: string
        -
          name: start_date
          in: query
          required: False
          schema:
            type: string
        -
          name: end_date
          in: query
          required: False
          schema:
            type: string
        -
          name: customer_vat
          in: query
          required: False
          schema:
            type: string
      responses:
        200:
          description: Successful response
      security:
        -
          BearerAuth:
  /v1/e-invoicing/{onboard_id}/credit-notes:
    post:
      summary: Report Credit Note Copy
      parameters:
        -
          name: onboard_id
          in: path
          required: True
          schema:
            type: string
      responses:
        200:
          description: Successful response
      requestBody:
        required: True
        content:
          application/json:
            schema:
              type: object
            example:
              creditnote_number: CN24
              creditnote_type: simplified
              billing_reference: Invoice16
              issue_date: 2026-01-06
              issue_time: 02:30:00
              language_id: ar
              doc_currency_code: SAR
              tax_currency_code: SAR
              send_notification:
                notification_type: whatsapp
                receiver_id: 918273238980
              customer_info:
                vat_number: 546254785693261
                tax_type: VAT
                registration_name: بشرى ع السويلم السويلم
                address:
                  street_name: King Fahd Road
                  building_number: 6589
                  plot_identification: 6589
                  city_subdivision_name: Riyadh
                  city_name: Riyadh
                  postal_zone: 11311
                  country: SA
                  country_subentity: 
                party_identification:
                  scheme: CRN
                  id: 2548964218
              supplier_info:
                vat_number: 311262046600003
                tax_type: VAT
                registration_name: Saudi Credit Bureau
                address:
                  street_name: Ghirnatah, Riyadh 13241
                  building_number: 2596
                  plot_identification: 2596
                  city_subdivision_name: Ghirnatah
                  city_name: Riyadh
                  postal_zone: 13241
                  country: SA
                  country_subentity: 
                party_identification:
                  scheme: CRN
                  id: 1010171097
              payment_means: cash
              payment_means_instruction_note: not needed
              allowance_charge:
                charge_indicator: False
                reason: discount
                amount: 0
                currency: 
                tax_category:
                  id: S
                  percent: 15
                  tax_type: VAT
              tax_total:
                currency: 
                tax_amount: 3.75
                tax_subtotal:
                  taxable_amount: 25
                  tax_amount: 3.75
                  tax_category:
                    id: S
                    percent: 15
                    tax_type: VAT
              legal_monitory_total:
                total_amount: 25
                tax_exclusive_amount: 25
                tax_inclusive_amount: 28.75
                payable_amount: 28.75
              invoice_lines:
                -
                  id: 1
                  unit_code: EA
                  quantity: 1
                  amount: 25
                  tax_total:
                    currency: SAR
                    tax_amount: 3.75
                    rounding_amount: 28.75
                  item:
                    name: Free Credit Report
                    classified_tax_category:
                      id: S
                      percent: 15
                      tax_type: VAT
                  price:
                    currency: SAR
                    price_per_unit: 25
                    base_unit_code: EA
                    allowance_charge:
                      charge_indicator: False
                      reason: discount
                      amount: 0
                      base_amount: 25
                      currency: SAR
              actual_delivery_date: 2026-01-02
      security:
        -
          BearerAuth:
    get:
      summary: List All CreditNotes
      parameters:
        -
          name: onboard_id
          in: path
          required: True
          schema:
            type: string
      responses:
        200:
          description: Successful response
      security:
        -
          BearerAuth:
  /v1/e-invoicing/{onboard_id}/debit-notes:
    post:
      summary: Report Debit Note
      parameters:
        -
          name: onboard_id
          in: path
          required: True
          schema:
            type: string
      responses:
        200:
          description: Successful response
      requestBody:
        required: True
        content:
          application/json:
            schema:
              type: object
            example:
              debitnote_number: dn-1008
              debitnote_type: simplified
              billing_reference: Invoice Number: inv-84; Invoice Issue Date: 2023-08-16
              issue_date: 2023-08-19
              issue_time: 10:09:00
              payment_means: cash
              payment_means_instruction_note: cancellation
              actual_delivery_date: 2023-08-21
              latest_delivery_date: 2023-08-23
              supplier_info:
                vat_number: 311262046600003
                tax_type: VAT
                registration_name: Goagile Technologies
                address:
                  street_name: some street
                  building_number: 1232
                  plot_identification: 123
                  city_subdivision_name: 3232112
                  city_name: Riyadh
                  postal_zone: 54321
                  country: SA
                party_identification:
                  scheme: CRN
                  id: 2332132133
              customer_info:
                vat_number: 2323233325
                tax_type: VAT
                registration_name: ABC Inc.
                address:
                  street_name: some street
                  building_number: 1232
                  plot_identification: 123
                  city_subdivision_name: 3232112
                  city_name: Riyadh
                  postal_zone: 12345
                  country: SA
                party_identification:
                  scheme: NAT
                  id: 767687876
              tax_total:
                currency: SAR
                tax_amount: 9
                tax_subtotal:
                  taxable_amount: 60
                  tax_amount: 9
                  tax_percent: 15
                  tax_category:
                    id: S
                    percent: 15
                    tax_type: VAT
              legal_monitory_total:
                total_amount: 60
                tax_exclusive_amount: 60
                tax_inclusive_amount: 69
                payable_amount: 69
              invoice_lines:
                -
                  id: 1
                  unit_code: pce
                  quantity: 20
                  amount: 60
                  tax_total:
                    currency: SAR
                    tax_amount: 9
                    rounding_amount: 69
                  item:
                    name: books
                    classified_tax_category:
                      id: S
                      percent: 15
                      tax_type: VAT
                  price:
                    currency: SAR
                    price_per_unit: 3
      security:
        -
          BearerAuth:
    get:
      summary: List All DebitNotes
      parameters:
        -
          name: onboard_id
          in: path
          required: True
          schema:
            type: string
      responses:
        200:
          description: Successful response
      security:
        -
          BearerAuth:
  /v1/e-invoicing/{onboard_id}/notify-config:
    post:
      summary: notify_config
      parameters:
        -
          name: onboard_id
          in: path
          required: True
          schema:
            type: string
      responses:
        200:
          description: Successful response
      requestBody:
        required: True
        content:
          application/json:
            schema:
              type: object
            example:
              active: True
              whatsapp_config:
                access_token: 684599e2b19c3
                instance_id: 6958DC6D80D0F
                message_template: Dear Customer, Your Invoice has been successfully processed.
      security:
        -
          BearerAuth:
  /v1/e-invoicing/NjcxOGYwZDc3YzczZGJlYTA2MjIwZmM0OjMxMTI2MjA0NjYwMDAwMzowMi1NT0xJTQ==/docs-xls:
    post:
      summary: Generate excel file
      parameters:
        -
          name: start_date
          in: query
          required: False
          schema:
            type: string
        -
          name: end_date
          in: query
          required: False
          schema:
            type: string
        -
          name: customer_vat
          in: query
          required: False
          schema:
            type: string
      responses:
        200:
          description: Successful response
      security:
        -
          BearerAuth:
  /v1/e-invoicing/{onboard_id}/tasks/3396df5a-96da-4c03-8625-d3e5aa2202a4:
    get:
      summary: Get Task
      parameters:
        -
          name: onboard_id
          in: path
          required: True
          schema:
            type: string
      responses:
        200:
          description: Successful response
      requestBody:
        required: True
        content:
          application/json:
            schema:
              type: object
            example:  
      security:
        -
          BearerAuth:
  /v1/e-invoicing/NjcxOGYwZDc3YzczZGJlYTA2MjIwZmM0OjMxMTI2MjA0NjYwMDAwMzowMi1NT0xJTQ==/docs-xls/5e1e695d-3c18-4d23-9f3c-71a8732e351c:
    get:
      summary: Download excel file
      parameters:
      responses:
        200:
          description: Successful response
      security:
        -
          BearerAuth:
  /v1/e-invoicing/{onboard_id}/invoices/pdfs/65871403655955:
    get:
      summary: Get Invoice PDF
      parameters:
        -
          name: onboard_id
          in: path
          required: True
          schema:
            type: string
      responses:
        200:
          description: Successful response
      security:
        -
          BearerAuth:
  /v1/e-invoicing/{onboard_id}/credit-notes/pdfs/1145581881415205:
    get:
      summary: Get Credit Note PDF
      parameters:
        -
          name: onboard_id
          in: path
          required: True
          schema:
            type: string
      responses:
        200:
          description: Successful response
      security:
        -
          BearerAuth:
  /v1/e-invoicing/{onboard_id}/credit-notes/dfd523d1-383e-45cd-89db-a6dcf8ea8584:
    get:
      summary: Get CreditNote XML
      parameters:
        -
          name: onboard_id
          in: path
          required: True
          schema:
            type: string
        -
          name: format
          in: query
          required: False
          schema:
            type: string
      responses:
        200:
          description: Successful response
      security:
        -
          BearerAuth:
  /v1/e-invoicing/{onboard_id}/invoices/11714086-c6eb-4a27-8bd4-859afdfde682:
    get:
      summary: Get Invoice XML
      parameters:
        -
          name: onboard_id
          in: path
          required: True
          schema:
            type: string
        -
          name: format
          in: query
          required: False
          schema:
            type: string
      responses:
        200:
          description: Successful response
      security:
        -
          BearerAuth:
  /v1/e-invoicing:
    get:
      summary: EGS-Info
      parameters:
      responses:
        200:
          description: Successful response
  /v1/e-invoicing/{onboard_id}/invoices/1145581881415212:
    get:
      summary: Get Invoice
      parameters:
        -
          name: onboard_id
          in: path
          required: True
          schema:
            type: string
      responses:
        200:
          description: Successful response
      security:
        -
          BearerAuth:
  /v1/e-invoicing/{onboard_id}/credit-notes/inv-1009:
    get:
      summary: Get CreditNote
      parameters:
        -
          name: onboard_id
          in: path
          required: True
          schema:
            type: string
      responses:
        200:
          description: Successful response
      security:
        -
          BearerAuth:
  /v1/e-invoicing/{onboard_id}/invoices/6552fcfcbeb186efc42daebe:
    get:
      summary: Get DebitNote
      parameters:
        -
          name: onboard_id
          in: path
          required: True
          schema:
            type: string
      responses:
        200:
          description: Successful response
      security:
        -
          BearerAuth: